-- =============================================================================
-- Entity:        Product
-- Layer:         Canonical Spine (Immutable Business Truth)
-- Purpose:       Represents a sellable item in the company's product catalog.
--                 Products are real-world nouns that exist independent of the
--                 platform. They derive from product catalog, SKU systems,
--                 and billing platforms. This table stores only immutable
--                 business truth — no derived scores, no AI opinion, no JSONB
--                 blobs. Relationships are stored in spine_relationships.
-- Source:        SPINE_DOMAIN.md §3.1, §3.4
--                 SPINE_INTELLIGENCE_AGENT.md §10.2 (spine_*.sql emission)
-- =============================================================================
-- D1 / SQLite DDL — generated by the Spine Intelligence Agent (Stage 8: Code Generation)
-- Rules:
--   • id TEXT PRIMARY KEY — UUID assigned by the pipeline, not generated in DB
--   • tenant_id, canonical_id TEXT NOT NULL
--   • version INTEGER NOT NULL DEFAULT 1 (append-only versioning)
--   • Typed columns only — no data JSON, no scope JSON, no relationships JSON
--   • Relationships stored in spine_relationships (typed edge table per SPINE_DOMAIN.md §3.4)
--   • provenance JSON NOT NULL DEFAULT '{}' — { source: '...', record_id: '...' }
--   • Timestamps are INTEGER (Unix epoch seconds)
-- =============================================================================

CREATE TABLE IF NOT EXISTS spine_products (
    id              TEXT PRIMARY KEY,
    tenant_id       TEXT NOT NULL,
    canonical_id    TEXT NOT NULL,
    version         INTEGER NOT NULL DEFAULT 1,

    -- Immutable business truth
    name            TEXT NOT NULL,
    description     TEXT,
    sku             TEXT,
    product_category TEXT,
    status          TEXT,
    unit_price      REAL,
    currency        TEXT,
    billing_frequency TEXT,
    unit_of_measure TEXT,
    effective_from  INTEGER,
    effective_until INTEGER,

    -- System
    provenance      JSON NOT NULL DEFAULT '{}',
    created_at      INTEGER,
    updated_at      INTEGER
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_spine_products_tenant_canonical ON spine_products(tenant_id, canonical_id);
CREATE INDEX IF NOT EXISTS idx_spine_products_tenant_version ON spine_products(tenant_id, canonical_id, version);
