-- =============================================================================
-- Entity:        spine_subscriptions
-- Layer:         Canonical Spine (Immutable Business Truth)
-- Purpose:       A recurring billing commitment — the immutable record of what
--                  a customer has subscribed to, when it renews, and how much
--                  it costs. Derived from Stripe, Zuora, or other billing systems.
-- Sources:        SPINE_DOMAIN.md §3.4 (Canonical Spine Schema Pattern)
--                 SPINE_INTELLIGENCE_AGENT.md §10 (Code Generation)
-- Domain:         account_success
-- Generated by:   Spine Intelligence Agent (Stage 8 — Code Generation)
-- =============================================================================

-- NOTE: No `data JSON`, no `scope JSON`, no `relationships JSON` in this table.
-- All typed relationships (e.g., Account → owns → Subscription,
-- Contract → renews → Subscription) are stored in `spine_relationships`.
-- This table contains ONLY immutable business truth about the subscription itself.

CREATE TABLE IF NOT EXISTS spine_subscriptions (
    -- ── Core identity ─────────────────────────────────────────────────────────
    id              TEXT PRIMARY KEY,                 -- UUID as text (assigned by pipeline)
    tenant_id       TEXT NOT NULL,                    -- tenant scoping (cross-tenant impossible)
    canonical_id    TEXT NOT NULL,                    -- stable identity; survives merges
    version         INTEGER NOT NULL DEFAULT 1,       -- append-only versioning

    -- ── Immutable business truth ────────────────────────────────────────────
    status          TEXT NOT NULL,                    -- active, canceled, past_due, trialing, paused, expired
    plan_name       TEXT,                             -- human-readable plan name (e.g., "Enterprise")
    plan_id         TEXT,                             -- external plan ID from billing system
    quantity        INTEGER,                          -- number of seats, units, or licenses
    start_date      TEXT,                             -- ISO 8601 date (YYYY-MM-DD) subscription started
    end_date        TEXT,                             -- ISO 8601 date (YYYY-MM-DD) current period ends
    renewal_date    TEXT,                             -- ISO 8601 date (YYYY-MM-DD) next renewal / auto-renew trigger
    billing_interval TEXT,                            -- monthly, yearly, quarterly, weekly, custom
    amount_usd      REAL,                             -- amount in USD (normalized for reporting)
    currency        TEXT,                             -- original currency code (USD, EUR, GBP, etc.)
    mrr_usd         REAL,                             -- monthly recurring revenue in USD
    arr_usd         REAL,                             -- annual recurring revenue in USD
    auto_renew      INTEGER NOT NULL DEFAULT 1,       -- boolean: 1 = auto-renews, 0 = manual/cancel at end
    payment_terms   TEXT,                             -- net_30, net_60, net_90, due_on_receipt, etc.

    -- ── System / provenance ─────────────────────────────────────────────────
    provenance      JSON NOT NULL DEFAULT '{}',       -- { source: "stripe", record_id: "sub_xxx" }
    created_at      INTEGER,                          -- Unix timestamp (seconds since epoch)
    updated_at      INTEGER                           -- Unix timestamp (seconds since epoch)
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
-- Fast lookup of the current (latest) version of a subscription by canonical identity
CREATE INDEX IF NOT EXISTS idx_spine_subscriptions_tenant_canonical
    ON spine_subscriptions(tenant_id, canonical_id);

-- Fast lookup of a specific version (enables time-travel and audit)
CREATE INDEX IF NOT EXISTS idx_spine_subscriptions_tenant_version
    ON spine_subscriptions(tenant_id, canonical_id, version);

-- Optional: fast status-based filtering within a tenant (e.g., "all active subs")
CREATE INDEX IF NOT EXISTS idx_spine_subscriptions_tenant_status
    ON spine_subscriptions(tenant_id, status);
