-- =============================================================================
-- Entity:        spine_persons
-- Layer:         Canonical Spine (Immutable Business Truth)
-- Purpose:       Represents a real-world human being (not a CRM contact).
--                A Person is a human who has a relationship with the business,
--                sourced from identity providers, CRMs, and manual entry.
-- Source:        docs/architecture/SPINE_DOMAIN.md §3.4
--                docs/architecture/SPINE_INTELLIGENCE_AGENT.md §10.2
-- Domain:        account_success
-- Generated by:  Spine Intelligence Agent — Code Generation Stage
-- =============================================================================

CREATE TABLE IF NOT EXISTS spine_persons (
    id              TEXT PRIMARY KEY,
    tenant_id       TEXT NOT NULL,
    canonical_id    TEXT NOT NULL,              -- stable identity; survives merges
    version         INTEGER NOT NULL DEFAULT 1,  -- append-only versioning

    -- Immutable business truth
    name            TEXT NOT NULL,
    email           TEXT NOT NULL,
    phone           TEXT,
    title           TEXT,
    department      TEXT,
    seniority       TEXT,                       -- e.g., c-level, vp, director, manager, individual
    role            TEXT,                       -- e.g., champion, economic_buyer, influencer, user
    timezone        TEXT,
    preferred_language TEXT,
    is_active       INTEGER NOT NULL DEFAULT 1,
    first_seen_at   INTEGER,                   -- Unix timestamp
    last_seen_at    INTEGER,                   -- Unix timestamp

    -- System
    provenance      JSON NOT NULL DEFAULT '{}', -- { source: 'salesforce', record_id: '...' }
    created_at      INTEGER,                   -- Unix timestamp
    updated_at      INTEGER,                   -- Unix timestamp

    -- NOTE: no `data JSON`, no `scope JSON`, no `relationships JSON`
    -- Relationships are stored in spine_relationships (typed edge table)

    UNIQUE(tenant_id, canonical_id, version)
);

CREATE INDEX IF NOT EXISTS idx_spine_persons_tenant_canonical ON spine_persons(tenant_id, canonical_id);
CREATE INDEX IF NOT EXISTS idx_spine_persons_tenant_version ON spine_persons(tenant_id, canonical_id, version);
CREATE INDEX IF NOT EXISTS idx_spine_persons_email ON spine_persons(tenant_id, email);
