-- =============================================================================
-- Entity:        Task
-- Layer:         Canonical Spine (Immutable Business Truth)
-- Purpose:       A unit of work assigned to a person. Tasks are real-world
--                 nouns that exist independent of the platform — they derive
--                 from task systems, CRMs, and project management tools.
--                 Each row is an immutable version of a Task. Updates append
--                 new versions (version column increments).
-- Source:        SPINE_DOMAIN.md §3.1, §3.4 (Canonical Spine Schema Pattern)
--                 SPINE_INTELLIGENCE_AGENT.md §10.2 (spine_*.sql emission)
-- Domain:         account_success
-- Generated by:   Spine Intelligence Agent (Stage 8 — Code Generation)
-- =============================================================================
-- D1 / SQLite DDL — generated by the Spine Intelligence Agent (Stage 8: Code Generation)
-- Rules:
--   • id TEXT PRIMARY KEY — UUID assigned by the pipeline, not generated in DB
--   • tenant_id, canonical_id TEXT NOT NULL
--   • version INTEGER NOT NULL DEFAULT 1 (append-only versioning)
--   • Typed columns only — no data JSON, no scope JSON, no relationships JSON
--   • Relationships stored in spine_relationships (typed edge table per SPINE_DOMAIN.md §3.4)
--   • provenance JSON NOT NULL DEFAULT '{}' — { source: '...', record_id: '...' }
--   • Timestamps are INTEGER (Unix epoch seconds)
-- =============================================================================

CREATE TABLE IF NOT EXISTS spine_tasks (
    -- ── Core identity ─────────────────────────────────────────────────────────
    id              TEXT PRIMARY KEY,                 -- UUID as text (assigned by pipeline)
    tenant_id       TEXT NOT NULL,                    -- tenant scoping (cross-tenant impossible by construction)
    canonical_id    TEXT NOT NULL,                    -- stable identity; survives merges and deduplication
    version         INTEGER NOT NULL DEFAULT 1,       -- append-only versioning; time-travel and audit support

    -- ── Immutable business truth ────────────────────────────────────────────────
    title           TEXT NOT NULL,                    -- human-readable task name
    description     TEXT,                             -- detailed description / notes
    status          TEXT NOT NULL DEFAULT 'open',    -- open, in_progress, completed, cancelled, blocked, deferred
    priority        TEXT,                             -- low, medium, high, urgent
    task_type       TEXT,                             -- follow_up, onboarding, support, qbr_prep, renewal, escalation, internal, external, custom
    due_date        TEXT,                             -- ISO 8601 date (YYYY-MM-DD) when task is due
    completed_at    INTEGER,                        -- Unix timestamp (seconds) when task was completed
    source_system   TEXT,                             -- origin system: 'salesforce', 'hubspot', 'asana', 'jira', 'notion', 'monday', 'manual', etc.
    external_id     TEXT,                             -- record ID in the source system (e.g., Salesforce Task ID)

    -- ── System / provenance ─────────────────────────────────────────────────
    provenance      JSON NOT NULL DEFAULT '{}',       -- { source: "salesforce", record_id: "00Txxx", sync_version: "v2" }
    created_at      INTEGER,                          -- Unix timestamp (seconds since epoch)
    updated_at      INTEGER                           -- Unix timestamp (seconds since epoch)
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
-- Fast lookup of the current (latest) version of a task by canonical identity
CREATE INDEX IF NOT EXISTS idx_spine_tasks_tenant_canonical
    ON spine_tasks(tenant_id, canonical_id);

-- Fast lookup of a specific version (enables time-travel and audit)
CREATE INDEX IF NOT EXISTS idx_spine_tasks_tenant_version
    ON spine_tasks(tenant_id, canonical_id, version);

-- Optional: fast status-based filtering within a tenant (e.g., "all open tasks")
CREATE INDEX IF NOT EXISTS idx_spine_tasks_tenant_status
    ON spine_tasks(tenant_id, status);

-- Optional: fast due-date filtering (e.g., "tasks due this week")
CREATE INDEX IF NOT EXISTS idx_spine_tasks_tenant_due
    ON spine_tasks(tenant_id, due_date);
