-- ============================================================================
-- Entity: spine_environments
-- Layer: Canonical Spine (Immutable Business Truth)
-- Purpose: Runtime environment boundaries (production, staging, development,
--          sandbox) where deployments and integrations are hosted.
--          Tracks cloud provider, region, and lifecycle status.
-- Source:  SPINE_DOMAIN.md §3.1, §3.4
--          SPINE_INTELLIGENCE_AGENT.md §10.2
-- Domain: account_success
-- Target:  D1 (SQLite-compatible)
-- Rules:
--   - id is assigned by the pipeline (TEXT UUID), NOT generated by DB
--   - Append-only versioning via version integer
--   - No data JSONB, no scope JSONB, no relationships JSONB
--   - Relationships go in spine_relationships (typed edge table)
--   - Timestamps are INTEGER (Unix epoch), NOT TIMESTAMPTZ
-- ============================================================================

CREATE TABLE IF NOT EXISTS spine_environments (
    id              TEXT PRIMARY KEY,
    tenant_id       TEXT NOT NULL,
    canonical_id    TEXT NOT NULL,              -- stable identity; survives merges
    version         INTEGER NOT NULL DEFAULT 1, -- append-only versioning

    -- Immutable business truth
    name            TEXT NOT NULL,              -- e.g. "Production AWS US-East-1"
    type            TEXT NOT NULL,              -- production, staging, development, sandbox
    cloud_provider  TEXT,                       -- aws, gcp, azure, on_premise, other
    region          TEXT,                       -- e.g. "us-east-1", "eu-west-1"
    status          TEXT NOT NULL DEFAULT 'active', -- active, inactive, decommissioned
    description     TEXT,                       -- human-readable description

    -- System
    provenance      JSON NOT NULL DEFAULT '{}', -- { source: "cmdb", record_id: "..." }
    created_at      INTEGER,                    -- Unix timestamp
    updated_at      INTEGER                     -- Unix timestamp
);

-- Indexes for tenant scoping, canonical lookup, and versioned retrieval
CREATE INDEX IF NOT EXISTS idx_spine_environments_tenant_canonical
    ON spine_environments(tenant_id, canonical_id);

CREATE INDEX IF NOT EXISTS idx_spine_environments_tenant_version
    ON spine_environments(tenant_id, canonical_id, version);

-- Optional: index for status filtering within a tenant
CREATE INDEX IF NOT EXISTS idx_spine_environments_tenant_status
    ON spine_environments(tenant_id, status) WHERE status IS NOT NULL;
