-- ============================================================================
-- Entity:        spine_deployments
-- Layer:         Canonical Spine (Immutable Business Truth)
-- Purpose:       Represents an installed instance of a product, sourced from
--                telemetry, monitoring, and CMDB systems. Each row is an
--                append-only version of a deployment record.
-- Source:        SPINE_DOMAIN.md §3.4, SPINE_INTELLIGENCE_AGENT.md §10.2
-- Domain:        account_success
-- Generated By:  Spine Intelligence Agent (Stage 8 — Code Generation)
-- ============================================================================

CREATE TABLE IF NOT EXISTS spine_deployments (
    -- Identity & versioning
    id              TEXT PRIMARY KEY,
    tenant_id       TEXT NOT NULL,
    canonical_id    TEXT NOT NULL,
    version         INTEGER NOT NULL DEFAULT 1,

    -- Immutable business truth
    name            TEXT NOT NULL,
    status          TEXT,                       -- 'active', 'inactive', 'provisioning', 'decommissioned'
    environment_type TEXT,                      -- 'production', 'staging', 'development', 'other'
    region          TEXT,                       -- geographic region / availability zone
    product_version TEXT,                       -- version of the product deployed
    deployment_date TEXT,                       -- ISO 8601 date (YYYY-MM-DD)
    decommission_date TEXT,                     -- ISO 8601 date (YYYY-MM-DD); NULL if still active
    last_seen_at    INTEGER,                    -- Unix timestamp of last telemetry
    endpoint        TEXT,                       -- URL or hostname where the deployment is accessible
    metadata        JSON,                       -- additional immutable telemetry / CMDB metadata

    -- System
    provenance      JSON NOT NULL DEFAULT '{}', -- { source: 'telemetry|cmdb|manual', record_id: '...' }
    created_at      INTEGER,                    -- Unix timestamp
    updated_at      INTEGER                     -- Unix timestamp
);

-- Indexes
CREATE INDEX IF NOT EXISTS idx_spine_deployments_tenant_canonical
    ON spine_deployments(tenant_id, canonical_id);

CREATE INDEX IF NOT EXISTS idx_spine_deployments_tenant_version
    ON spine_deployments(tenant_id, canonical_id, version);

CREATE INDEX IF NOT EXISTS idx_spine_deployments_tenant_status
    ON spine_deployments(tenant_id, status)
    WHERE status IS NOT NULL;

CREATE INDEX IF NOT EXISTS idx_spine_deployments_tenant_last_seen
    ON spine_deployments(tenant_id, last_seen_at)
    WHERE last_seen_at IS NOT NULL;
