-- ============================================================================
-- Entity:        spine_initiatives
-- Layer:         Canonical Spine (Immutable Business Truth)
-- Purpose:       Represents a program of work to achieve an objective.
--                  Initiatives are real-world programs of work (e.g., onboarding
--                  campaigns, expansion plays, migration projects) that exist
--                  independently of the platform. They derive from project
--                  management systems, manual entry, and system events.
-- Source:        SPINE_DOMAIN.md §3.1, §3.4
--                SPINE_INTELLIGENCE_AGENT.md §10.2 (Code Generation)
-- Generated By:  Spine Intelligence Agent — Stage 8 Code Generation
-- Domain:        account_success
-- Target:        D1 (SQLite-compatible)
-- ============================================================================

CREATE TABLE IF NOT EXISTS spine_initiatives (
    -- Core identity (append-only versioning)
    id              TEXT PRIMARY KEY,                         -- UUID as text, assigned by the pipeline
    tenant_id       TEXT NOT NULL,                            -- multi-tenant isolation
    canonical_id    TEXT NOT NULL,                            -- stable identity; survives merges
    version         INTEGER NOT NULL DEFAULT 1,              -- append-only versioning

    -- Immutable business truth — typed columns only (no data JSON, no scope JSON, no relationships JSON)
    name            TEXT NOT NULL,                            -- initiative name / title
    description     TEXT,                                    -- detailed description of the initiative
    status          TEXT,                                    -- e.g., 'planned', 'active', 'completed', 'cancelled', 'on_hold'
    priority        TEXT,                                    -- e.g., 'critical', 'high', 'medium', 'low'
    category        TEXT,                                    -- e.g., 'onboarding', 'expansion', 'renewal', 'migration', 'optimization'
    start_date      TEXT,                                    -- ISO 8601 date (YYYY-MM-DD); planned or actual start
    target_end_date TEXT,                                    -- ISO 8601 date (YYYY-MM-DD); target completion
    actual_end_date TEXT,                                    -- ISO 8601 date (YYYY-MM-DD); actual completion (NULL until done)
    budget          REAL,                                    -- budget amount in tenant's currency
    budget_currency TEXT,                                    -- ISO 4217 currency code (e.g., 'USD', 'EUR')
    progress_percent REAL,                                   -- completion percentage (0.0 – 1.0)
    outcome_summary TEXT,                                    -- summary of results, outcomes, or post-mortem

    -- System
    provenance      JSON NOT NULL DEFAULT '{}',             -- { source: 'salesforce' | 'jira' | 'manual' | 'system', record_id: '...', imported_at: 1234567890 }
    created_at      INTEGER,                                 -- Unix timestamp (seconds since epoch)
    updated_at      INTEGER                                  -- Unix timestamp (seconds since epoch)

    -- NOTE: No `data JSON`, no `scope JSON`, no `relationships JSON`.
    -- Relationships (e.g., Initiative -> achieves -> Objective, Initiative -> owned_by -> Person)
    -- are stored in the typed edge table `spine_relationships` (SPINE_DOMAIN.md §3.4).
);

-- Indexes for tenant-scoped lookups and append-only versioning
CREATE INDEX IF NOT EXISTS idx_spine_initiatives_tenant_canonical
    ON spine_initiatives(tenant_id, canonical_id);

CREATE INDEX IF NOT EXISTS idx_spine_initiatives_tenant_version
    ON spine_initiatives(tenant_id, canonical_id, version);

-- Optional: index for common query patterns (status filtering by tenant)
CREATE INDEX IF NOT EXISTS idx_spine_initiatives_tenant_status
    ON spine_initiatives(tenant_id, status)
    WHERE status IS NOT NULL;
