-- =============================================================================
-- Entity:        Activity
-- Layer:         Canonical Spine (Immutable Business Truth)
-- Purpose:       A platform-level operational primitive representing any
--                business action, interaction, or logged event. Activities are
--                universal across all domains — they capture what happened,
--                when it happened, how it happened, and what resulted.
--                Examples include calls, emails, notes, logged tasks, social
--                touches, and system events. Each row is an immutable version;
--                updates append new versions (version column increments).
-- Source:        SPINE_DOMAIN.md §3.1, §3.4 (Canonical Spine Schema Pattern)
--                SPINE_INTELLIGENCE_AGENT.md §10.2 (spine_*.sql emission)
-- Domain:        platform
-- Generated by:   Spine Domain Architect
-- =============================================================================
-- D1 / SQLite DDL — generated for the IntegrateWise Platform Canonical Spine
-- Rules:
--   • id TEXT PRIMARY KEY — UUID assigned by the pipeline, not generated in DB
--   • tenant_id, canonical_id TEXT NOT NULL
--   • version INTEGER NOT NULL DEFAULT 1 (append-only versioning)
--   • Typed columns only — no data JSON, no scope JSON, no relationships JSON
--   • Relationships stored in spine_relationships (typed edge table per SPINE_DOMAIN.md §3.4)
--   • provenance JSON NOT NULL DEFAULT '{}' — structured: { source, record_id, actor }
--   • Timestamps are INTEGER (Unix epoch seconds)
-- =============================================================================

CREATE TABLE IF NOT EXISTS spine_activities (
    -- ── Core identity ─────────────────────────────────────────────────────────
    id              TEXT PRIMARY KEY,                 -- UUID as text (assigned by pipeline)
    tenant_id       TEXT NOT NULL,                    -- tenant scoping; cross-tenant impossible by construction
    canonical_id    TEXT NOT NULL,                    -- stable identity; survives merges and deduplication
    version         INTEGER NOT NULL DEFAULT 1,       -- append-only versioning; time-travel and audit support

    -- ── Immutable business truth ──────────────────────────────────────────────
    -- Activity represents a universal business action or interaction.
    -- All columns are typed; no domain-specific fields (e.g., cs_score, churn_risk).
    -- Those belong in Dynamic Memory, not the Canonical Spine.
    title           TEXT NOT NULL,                    -- human-readable subject / summary of the activity
    activity_type   TEXT NOT NULL,                    -- call, email, meeting, note, task, social, system_event, custom, etc.
    status          TEXT NOT NULL DEFAULT 'completed', -- planned, scheduled, in_progress, completed, cancelled, no_show, deferred
    direction       TEXT,                             -- inbound, outbound, internal — who initiated the interaction
    medium          TEXT,                             -- phone, email, video, in_person, chat, sms, social, web, api, other
    description     TEXT,                             -- body content, notes, or detailed description of what occurred
    outcome         TEXT,                             -- brief result or outcome of the activity (e.g., "left voicemail", "agreed to renewal")

    -- Timing
    occurred_at     INTEGER,                          -- Unix timestamp (seconds) when the activity took place in the real world
    started_at      INTEGER,                          -- Unix timestamp (seconds) when the activity began
    ended_at        INTEGER,                          -- Unix timestamp (seconds) when the activity concluded
    duration_seconds INTEGER,                         -- computed duration of the activity in seconds
    is_all_day      INTEGER NOT NULL DEFAULT 0,       -- 0 = false, 1 = true (all-day activity, no specific time)
    timezone        TEXT,                             -- IANA timezone identifier (e.g., "America/New_York")

    -- Source system tracking
    source_system   TEXT,                             -- origin system: 'salesforce', 'hubspot', 'intercom', 'zendesk', 'slack', 'manual', 'system', etc.
    external_id     TEXT,                             -- record ID in the source system (e.g., Salesforce Activity ID, HubSpot Engagement ID)

    -- ── System / provenance ───────────────────────────────────────────────────
    -- provenance is structured JSON: { source: "...", record_id: "...", actor: "..." }
    --   source  — originating system or integration (e.g., "salesforce", "hubspot", "manual", "system")
    --   record_id — the native ID from the source system (e.g., "0D2xxx")
    --   actor   — the person, agent, or system that performed or recorded this activity
    provenance      JSON NOT NULL DEFAULT '{}',
    created_at      INTEGER,                          -- Unix timestamp (seconds since epoch) when this version was created
    updated_at      INTEGER,                          -- Unix timestamp (seconds since epoch) when this version was last updated

    -- Ensure uniqueness of a specific version for a given canonical entity within a tenant
    UNIQUE(tenant_id, canonical_id, version)
);

-- ── Indexes ─────────────────────────────────────────────────────────────────
-- Fast lookup of the current (latest) version of an activity by canonical identity
CREATE INDEX IF NOT EXISTS idx_spine_activities_tenant_canonical
    ON spine_activities(tenant_id, canonical_id);

-- Fast lookup of a specific version (enables time-travel and audit)
CREATE INDEX IF NOT EXISTS idx_spine_activities_tenant_version
    ON spine_activities(tenant_id, canonical_id, version);

-- Optional: fast filtering by activity type within a tenant (e.g., "all emails")
CREATE INDEX IF NOT EXISTS idx_spine_activities_tenant_type
    ON spine_activities(tenant_id, activity_type);

-- Optional: fast status-based filtering within a tenant (e.g., "all completed activities")
CREATE INDEX IF NOT EXISTS idx_spine_activities_tenant_status
    ON spine_activities(tenant_id, status);

-- Optional: fast temporal lookup (e.g., "activities in the last 7 days")
CREATE INDEX IF NOT EXISTS idx_spine_activities_tenant_occurred
    ON spine_activities(tenant_id, occurred_at);
