-- =============================================================================
-- Entity:        Evidence
-- Layer:         Canonical Spine (Operational Primitive)
-- Purpose:       Evidence is a first-class platform operational primitive that
--                 provides citation, verification, and proof for any claim in
--                 the system. It supports decisions, signals, outcomes, memories,
--                 and all other root concepts by anchoring assertions to verifiable
--                 sources. Each row is an immutable version of an Evidence record.
--                 Updates append new versions (version column increments).
-- Source:        SPINE_DOMAIN.md §1.2 (7 Operational Primitives), §3.4
--                 SPINE_INTELLIGENCE_AGENT.md §10.2
-- Domain:         platform (universal across all business domains)
-- Generated by:   Spine Domain Architect
-- =============================================================================
-- D1 / SQLite DDL
-- Rules:
--   • id TEXT PRIMARY KEY — UUID assigned by the pipeline
--   • tenant_id, canonical_id TEXT NOT NULL
--   • version INTEGER NOT NULL DEFAULT 1 (append-only versioning)
--   • Typed columns only — no data JSON, no scope JSON, no relationships JSON
--   • Relationships stored in spine_relationships (typed edge table)
--   • provenance JSON NOT NULL DEFAULT '{}' — { source: "...", record_id: "...", actor: "..." }
--   • Timestamps are INTEGER (Unix epoch seconds)
-- =============================================================================

CREATE TABLE IF NOT EXISTS spine_evidence (
    -- ── Core identity ─────────────────────────────────────────────────────────
    id              TEXT PRIMARY KEY,                 -- UUID as text (assigned by pipeline)
    tenant_id       TEXT NOT NULL,                    -- tenant scoping (cross-tenant impossible by construction)
    canonical_id    TEXT NOT NULL,                    -- stable identity; survives merges and deduplication
    version         INTEGER NOT NULL DEFAULT 1,       -- append-only versioning; time-travel and audit support

    -- ── Immutable business truth ────────────────────────────────────────────────
    evidence_type   TEXT NOT NULL,                    -- 'link', 'document', 'metric', 'quote', 'snapshot', 'audit_log', 'calculation', 'observation', 'reference', 'test_result'
    title           TEXT,                             -- human-readable title or label
    description     TEXT,                             -- detailed description of the evidence
    source          TEXT,                             -- human-readable source name (e.g., 'Salesforce', 'Jira', 'Manual Upload')
    source_url      TEXT,                             -- URL or reference path to the evidence origin
    content         TEXT,                             -- the actual evidence content (quote, text, metric value, serialized data)
    content_hash    TEXT,                             -- hash of content for integrity verification
    verification_status TEXT DEFAULT 'unverified',  -- 'verified', 'unverified', 'disputed', 'superseded'
    verified_at     INTEGER,                          -- Unix timestamp (seconds) when evidence was verified
    verified_by     TEXT,                             -- person or agent identity who verified
    confidence      REAL DEFAULT 0.5,               -- 0.0 to 1.0; confidence in the evidence validity

    -- ── System / provenance ─────────────────────────────────────────────────
    provenance      JSON NOT NULL DEFAULT '{}',       -- { source: "...", record_id: "...", actor: "..." }
    created_at      INTEGER,                          -- Unix timestamp (seconds since epoch)
    updated_at      INTEGER                           -- Unix timestamp (seconds since epoch)
);

-- ── Indexes ──────────────────────────────────────────────────────────────────
-- Fast lookup of the current (latest) version of an evidence record by canonical identity
CREATE INDEX IF NOT EXISTS idx_spine_evidence_tenant_canonical
    ON spine_evidence(tenant_id, canonical_id);

-- Fast lookup of a specific version (enables time-travel and audit)
CREATE INDEX IF NOT EXISTS idx_spine_evidence_tenant_version
    ON spine_evidence(tenant_id, canonical_id, version);

-- Optional: fast evidence-type filtering within a tenant (e.g., "all metric evidence")
CREATE INDEX IF NOT EXISTS idx_spine_evidence_tenant_type
    ON spine_evidence(tenant_id, evidence_type);

-- Optional: fast verification-status filtering (e.g., "all verified evidence")
CREATE INDEX IF NOT EXISTS idx_spine_evidence_tenant_status
    ON spine_evidence(tenant_id, verification_status);
