-- IntegrateWise Platform :: Dynamic Memory Layer
-- Domain: Health Memory
-- Description: Ephemeral, AI-generated health observations and healthcheck signals for Spine entities.
-- Layer: Domain-specific (derived from platform health signals, follows L1-L8 pipeline semantics)
-- Target: Cloudflare D1 (SQLite-compatible)

-- =============================================================================
-- Table: memory_health
-- =============================================================================
-- Stores health-related ephemeral observations generated by AI agents, monitors,
-- or healthcheck processes. Each record is opinionated (confidence-scored),
-- time-bound (TTL + expires_at), and anchored to a canonical Spine entity via
-- canonical_id + entity_type. All records are event-sourced via episode_id
-- linking to the OODA cycle.
-- =============================================================================

CREATE TABLE IF NOT EXISTS memory_health (
    -- Primary key
    id TEXT PRIMARY KEY NOT NULL,

    -- Tenant isolation
    tenant_id TEXT NOT NULL,

    -- Spine entity reference (foreign concept; enforced by application layer)
    canonical_id TEXT NOT NULL,
    entity_type TEXT NOT NULL,

    -- Optimistic versioning for concurrent updates
    version INTEGER NOT NULL DEFAULT 1,

    -- Ephemeral scoring: how much should the system trust this observation?
    confidence REAL NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),

    -- Identity of the agent, monitor, or process that generated this memory
    generated_by TEXT NOT NULL,

    -- Event sourcing: OODA episode that produced this memory
    episode_id TEXT NOT NULL,

    -- Memory classification within health domain (e.g., 'healthcheck', 'degradation', 'recovery', 'anomaly')
    memory_type TEXT NOT NULL,

    -- Lifecycle status (e.g., 'active', 'stale', 'superseded', 'resolved', 'expired')
    status TEXT NOT NULL DEFAULT 'active',

    -- Human-readable summary / AI-generated observation text
    content TEXT NOT NULL DEFAULT '',

    -- Source system that emitted the raw signal (e.g., 'spine-health-monitor', 'gateway-probe', 'twin-check')
    provenance TEXT NOT NULL DEFAULT 'unknown',

    -- Time-to-live in seconds (domain-specific TTL; 0 or negative = persistent)
    TTL INTEGER NOT NULL DEFAULT 86400,

    -- Absolute expiration timestamp (UTC)
    expires_at DATETIME NOT NULL,

    -- Creation / update timestamps (UTC)
    created_at DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);

-- =============================================================================
-- Indexes
-- =============================================================================

-- Lookup by tenant + canonical entity (most common read path)
CREATE INDEX IF NOT EXISTS idx_memory_health_tenant_canonical
    ON memory_health (tenant_id, canonical_id);

-- Lookup by tenant + entity type (for bulk operations on a specific Spine type)
CREATE INDEX IF NOT EXISTS idx_memory_health_tenant_entity_type
    ON memory_health (tenant_id, entity_type);

-- Lookup by tenant + memory type (for filtering by health signal classification)
CREATE INDEX IF NOT EXISTS idx_memory_health_tenant_memory_type
    ON memory_health (tenant_id, memory_type);

-- Lookup by tenant + status (for lifecycle sweeps: e.g., "find all stale health memories")
CREATE INDEX IF NOT EXISTS idx_memory_health_tenant_status
    ON memory_health (tenant_id, status);

-- Ranking by confidence for a given canonical entity (promote high-confidence observations)
CREATE INDEX IF NOT EXISTS idx_memory_health_canonical_confidence
    ON memory_health (canonical_id, confidence DESC);

-- Time-bound sweep: find expired / soon-to-expire memories for a tenant
CREATE INDEX IF NOT EXISTS idx_memory_health_tenant_expires
    ON memory_health (tenant_id, expires_at);
