-- IntegrateWise Platform: Dynamic Memory Layer
-- Table: memory_twin_memory
-- Layer: L1 (Twin) — Raw, ephemeral AI-generated observations
-- Target: Cloudflare D1 (SQLite-compatible)
-- ============================================================================

-- ---------------------------------------------------------------------------
-- L1 Twin Memory
-- ---------------------------------------------------------------------------
-- Twin Memory represents the rawest, most ephemeral layer of the Dynamic
-- Memory pipeline. It captures real-time observations, inferences, and
-- situational awareness generated by the AI twin about a canonical Spine
-- entity. These memories are opinionated (confidence-scored), event-sourced
-- (episode-linked), and short-lived (TTL-enforced). They are NOT the source
-- of truth — they are transient projections that feed into higher layers
-- (L2-L8) of the memory pipeline.
--
-- Key characteristics:
--   - Every record references a canonical Spine entity via canonical_id + entity_type
--   - Confidence is mandatory (0.0–1.0) and reflects the model's certainty
--   - generated_by identifies the model/agent that produced the memory
--   - episode_id links the memory to a specific OODA cycle execution
--   - TTL and expires_at are mandatory for L1 twin memories
--   - Graph-native: edges can reference other memory records or Spine entities
--   - Projection-friendly: indexed for slicing by tenant, entity, type, status, and expiry
-- ============================================================================

CREATE TABLE IF NOT EXISTS memory_twin_memory (
    id               TEXT PRIMARY KEY NOT NULL,
                     -- Unique identifier for this memory record (UUID v4)

    tenant_id        TEXT NOT NULL,
                     -- Multi-tenant isolation boundary

    canonical_id     TEXT NOT NULL,
                     -- Foreign logical key to the canonical Spine entity.
                     -- All memory MUST reference a Spine entity.

    entity_type      TEXT NOT NULL,
                     -- Type of the referenced Spine entity (e.g., 'user', 'team', 'project', 'asset').
                     -- Combined with canonical_id to fully identify the Spine entity.

    version          INTEGER NOT NULL DEFAULT 1,
                     -- Optimistic locking version for concurrency control.
                     -- Incremented on every update.

    confidence       REAL NOT NULL,
                     -- Model confidence score (0.0 = no confidence, 1.0 = absolute certainty).
                     -- Opinionated: required for all memory records.

    generated_by     TEXT NOT NULL,
                     -- Identifier of the model or agent that generated this memory.
                     -- e.g., 'gpt-4o', 'twin-v2', 'classifier-prod'.
                     -- Opinionated: required for all memory records.

    episode_id       TEXT NOT NULL,
                     -- OODA cycle execution ID that produced this memory.
                     -- Event-sourced: links memory to the decision loop that created it.

    memory_type      TEXT NOT NULL DEFAULT 'L1',
                     -- Memory pipeline layer (L1 twin, L2 intake, L3 triage, L4 evolution,
                     -- L5 promotion, L6 approval, L7 organizational, L8 knowledge).
                     -- For this table, value is always 'L1' (twin memory).

    status           TEXT NOT NULL DEFAULT 'active',
                     -- Lifecycle state: 'active', 'expired', 'replaced', 'superseded', 'promoted'.
                     -- Drives TTL cleanup and promotion pipeline decisions.

    content          TEXT,
                     -- Human-readable or structured textual content of the memory.
                     -- For structured data, prefer typed columns where possible.

    provenance       TEXT,
                     -- Source context: how this memory was derived.
                     -- e.g., 'inference_from_signal', 'twin_observation', 'llm_generation',
                     -- 'prompt_template_v3', 'human_feedback_loop'.

    TTL              INTEGER NOT NULL,
                     -- Time-to-live in seconds. Must be > 0 for L1 twin memories.
                     -- Controls automatic expiry and cleanup scheduling.

    expires_at       TEXT NOT NULL,
                     -- Absolute expiry timestamp (ISO 8601). Must be after created_at.
                     -- Used for deterministic TTL enforcement and index-driven eviction.
                     -- Use SQLite-compatible format: 'YYYY-MM-DD HH:MM:SS'.

    created_at       TEXT NOT NULL DEFAULT (datetime('now')),
                     -- Record creation timestamp (ISO 8601 in SQLite format).

    updated_at       TEXT NOT NULL DEFAULT (datetime('now')),
                     -- Last modification timestamp (ISO 8601).

    -- ------------------------------------------------------------------------
    -- Table-level constraints
    -- ------------------------------------------------------------------------
    CONSTRAINT chk_confidence_range
        CHECK (confidence >= 0.0 AND confidence <= 1.0),

    CONSTRAINT chk_ttl_positive
        CHECK (TTL > 0),

    CONSTRAINT chk_expires_after_created
        CHECK (expires_at > created_at)
);

-- ============================================================================
-- Indexes for query patterns and projection slicing
-- ============================================================================

-- Multi-tenant entity lookup: find all twin memories for a specific Spine entity
CREATE INDEX IF NOT EXISTS idx_memory_twin_tenant_canonical
    ON memory_twin_memory (tenant_id, canonical_id);

-- Entity-type projection: slice memories by the type of Spine entity they describe
CREATE INDEX IF NOT EXISTS idx_memory_twin_tenant_entity_type
    ON memory_twin_memory (tenant_id, entity_type);

-- Memory-layer projection: filter by pipeline layer (L1-L8 or domain-specific)
CREATE INDEX IF NOT EXISTS idx_memory_twin_tenant_memory_type
    ON memory_twin_memory (tenant_id, memory_type);

-- Status-driven queries: filter by lifecycle state (active, expired, promoted, etc.)
CREATE INDEX IF NOT EXISTS idx_memory_twin_tenant_status
    ON memory_twin_memory (tenant_id, status);

-- Confidence-ranked retrieval per entity: order observations by model certainty
CREATE INDEX IF NOT EXISTS idx_memory_twin_canonical_confidence
    ON memory_twin_memory (canonical_id, confidence DESC);

-- TTL eviction and time-window queries: find memories expiring within a horizon
CREATE INDEX IF NOT EXISTS idx_memory_twin_tenant_expires
    ON memory_twin_memory (tenant_id, expires_at);

-- ============================================================================
-- Application-layer recommendation: version + updated_at management
-- ============================================================================
-- D1 (and SQLite generally) has limited support for recursive triggers.
-- It is recommended to manage `version` and `updated_at` in the application
-- layer or via the ORM/data access layer:
--
--   UPDATE memory_twin_memory
--   SET    content = ?,
--          updated_at = datetime('now'),
--          version = version + 1
--   WHERE  id = ? AND version = ?;
--
-- This pattern provides optimistic locking without trigger recursion.
-- ============================================================================

