------------------------------------------------------------------------------
-- IntegrateWise Platform :: Dynamic Memory Layer
-- Table: memory_insights
-- Target: Cloudflare D1 (SQLite-compatible)
--
-- DESCRIPTION:
--   Stores ephemeral, AI-generated insights extracted from platform signals.
--   These insights are opinions — NOT the source of truth. Each record is
--   anchored to a canonical Spine entity (canonical_id + entity_type) and
--   is scoped to a tenant, versioned, and time-bounded (TTL / expires_at).
--
--   Insights are generated during OODA episodes (episode_id) by specific
--   agents or pipelines (generated_by) and carry a confidence score.
--
--   LAYER CLASSIFICATION: Domain-specific
--   This table holds cross-cutting insight memory derived from platform
--   signals (health, risk, sentiment, anomaly, trend, etc.) and follows
--   the standard L1-L8 promotion pipeline. Insights typically originate
--   at L2 (intake) or L3 (triage) and may be promoted to L5-L8.
--
-- RULES:
--   - Every row MUST reference a Spine entity via canonical_id + entity_type.
--   - Confidence is mandatory (0.0–1.0).
--   - generated_by is mandatory (agent / pipeline identifier).
--   - episode_id is mandatory (links to OODA cycle).
--   - TTL and expires_at are mandatory (except for promoted L6-L8 records).
--   - No JSONB for core business data; structured fields are typed columns.
--   - content is TEXT (human-readable narrative or serialized insight).
--
-- INDEX STRATEGY:
--   - tenant + canonical_id: fast lookup of all insights for an entity.
--   - tenant + entity_type: scan insights by entity class.
--   - tenant + memory_type: filter by pipeline layer / insight category.
--   - tenant + status: filter by lifecycle state (active, expired, etc.).
--   - canonical_id + confidence: rank insights by certainty for an entity.
--   - tenant + expires_at: sweeping / TTL cleanup jobs.
------------------------------------------------------------------------------

-- Drop for idempotent re-runs (optional — comment out in production migration)
-- DROP TABLE IF EXISTS memory_insights;

CREATE TABLE IF NOT EXISTS memory_insights (
    -- Primary identifier
    id              TEXT PRIMARY KEY,          -- UUID v7 (or KSUID) generated by the service layer

    -- Multi-tenancy & Spine linkage
    tenant_id       TEXT NOT NULL,             -- workspace / org / tenant slug
    canonical_id    TEXT NOT NULL,             -- FK to a Spine entity (e.g. company:uuid, user:uuid)
    entity_type     TEXT NOT NULL,             -- Spine entity type discriminator (e.g. 'company', 'user', 'integration')

    -- Versioning
    version         INTEGER NOT NULL DEFAULT 1, -- monotonic version counter per (tenant, canonical_id, memory_type)

    -- Opinionated metadata
    confidence      REAL NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),
    generated_by    TEXT NOT NULL,             -- agent / pipeline identifier that produced this insight (e.g. 'health-agent-v3', 'triage-pipeline')
    episode_id      TEXT NOT NULL,             -- OODA cycle episode that generated this insight

    -- Memory classification & lifecycle
    memory_type     TEXT NOT NULL CHECK (memory_type IN (
                        'L1_twin', 'L2_intake', 'L3_triage', 'L4_evolution',
                        'L5_promotion_queue', 'L6_approval', 'L7_organizational', 'L8_knowledge',
                        'domain_health', 'domain_risk', 'domain_sentiment', 'domain_anomaly',
                        'domain_trend', 'domain_recommendation', 'domain_forecast'
                    )),
    status          TEXT NOT NULL DEFAULT 'active' CHECK (status IN (
                        'active', 'pending_review', 'promoted', 'superseded', 'expired', 'archived', 'rejected'
                    )),

    -- Content & provenance
    content         TEXT NOT NULL,             -- human-readable insight text (or markdown)
    provenance      TEXT,                      -- audit trail: source signals, intermediate reasoning, upstream memory IDs

    -- Time-to-live & expiry
    TTL             INTEGER,                   -- seconds until expiry (NULL = persistent, allowed only for L6-L8)
    expires_at      INTEGER,                   -- Unix epoch timestamp (seconds) when this memory becomes invalid
    created_at      INTEGER NOT NULL DEFAULT (unixepoch()),
    updated_at      INTEGER NOT NULL DEFAULT (unixepoch()),

    -- Constraints
    CONSTRAINT fk_canonical CHECK (canonical_id <> ''),
    CONSTRAINT fk_entity_type CHECK (entity_type <> ''),
    CONSTRAINT fk_tenant CHECK (tenant_id <> ''),
    CONSTRAINT fk_episode CHECK (episode_id <> ''),
    CONSTRAINT fk_generated_by CHECK (generated_by <> ''),

    -- TTL enforcement: L6-L8 may have NULL TTL (persistent), all others must have TTL
    CONSTRAINT ttl_layer CHECK (
        (memory_type IN ('L6_approval', 'L7_organizational', 'L8_knowledge') AND TTL IS NULL) OR
        (TTL IS NOT NULL AND TTL > 0)
    ),

    -- expires_at must align with TTL if present
    CONSTRAINT expires_aligned CHECK (
        (TTL IS NULL AND expires_at IS NULL) OR
        (TTL IS NOT NULL AND expires_at IS NOT NULL AND expires_at > created_at)
    )
);

------------------------------------------------------------------------------
-- INDEXES
------------------------------------------------------------------------------

-- 1. Tenant + canonical entity: look up all insights for a given Spine record
CREATE INDEX IF NOT EXISTS idx_mem_insights_tenant_canonical
    ON memory_insights (tenant_id, canonical_id);

-- 2. Tenant + entity type: scan insights by entity class (e.g. all company insights)
CREATE INDEX IF NOT EXISTS idx_mem_insights_tenant_entity_type
    ON memory_insights (tenant_id, entity_type);

-- 3. Tenant + memory type: filter by pipeline layer or domain category
CREATE INDEX IF NOT EXISTS idx_mem_insights_tenant_memory_type
    ON memory_insights (tenant_id, memory_type);

-- 4. Tenant + status: filter by lifecycle state (active, expired, etc.)
CREATE INDEX IF NOT EXISTS idx_mem_insights_tenant_status
    ON memory_insights (tenant_id, status);

-- 5. Canonical + confidence: rank insights by confidence for a specific entity
CREATE INDEX IF NOT EXISTS idx_mem_insights_canonical_confidence
    ON memory_insights (canonical_id, confidence DESC);

-- 6. Tenant + expires_at: sweep / TTL cleanup jobs
CREATE INDEX IF NOT EXISTS idx_mem_insights_tenant_expires
    ON memory_insights (tenant_id, expires_at);

-- 7. Episode lookup: find all insights generated by a specific OODA cycle
CREATE INDEX IF NOT EXISTS idx_mem_insights_episode
    ON memory_insights (episode_id);

-- 8. Generated-by lookup: trace lineage by agent / pipeline
CREATE INDEX IF NOT EXISTS idx_mem_insights_generated_by
    ON memory_insights (generated_by, created_at DESC);

------------------------------------------------------------------------------
-- TABLE COMMENT (SQLite stores via separate PRAGMA or application layer)
-- The canonical comment is placed here as a SQL comment block for readability.
-- If your migration runner supports it, uncomment the INSERT below to store
-- metadata in a registry table (not standard SQLite).
--
-- INSERT INTO memory_schema_registry (table_name, description, layer)
-- VALUES ('memory_insights', 'Ephemeral AI-generated insights from platform signals', 'domain_specific');
------------------------------------------------------------------------------
