--
-- memory_forecast
-- Layer: Dynamic Memory (AI-created, ephemeral, opinionated)
-- TTL: 30 days
-- Purpose: Predicted revenue, churn, expansion, renewal, and other account-level
--          forecast outcomes generated by ML models or heuristic agents.
--          Links to the Canonical Spine via entity_type + canonical_id.
-- Source: SPINE_DOMAIN.md §4.3 (Dynamic Memory Schema pattern)
--         SPINE_DOMAIN.md §4.1 (Forecast memory type — TTL 30 days)
--         SPINE_INTELLIGENCE_AGENT.md §7.2 (Memory Classification)
-- Target: D1 / SQLite
--

CREATE TABLE IF NOT EXISTS memory_forecast (
    id                  TEXT PRIMARY KEY,
    tenant_id           TEXT NOT NULL,
    -- Link to Canonical Spine (always)
    entity_type         TEXT NOT NULL,              -- 'account', 'organization', etc.
    canonical_id        TEXT NOT NULL,              -- stable identity in the Spine
    -- Forecast memory content
    forecast_type       TEXT NOT NULL,              -- 'revenue', 'churn', 'expansion', 'renewal', 'nrr', 'logo_retention', 'arpu'
    forecast_value      REAL,                       -- predicted numeric value (e.g., forecasted revenue in base currency)
    forecast_value_label TEXT,                      -- 'high-growth', 'stable', 'declining', 'at-risk', 'accelerating'
    currency            TEXT,                       -- 'USD', 'EUR', 'GBP', etc.
    probability         REAL,                       -- 0.0–1.0 likelihood of the forecasted outcome
    score_label         TEXT,                       -- 'likely', 'uncertain', 'improbable', 'high-confidence'
    reasoning           TEXT,                       -- LLM-generated or heuristic explanation of the forecast
    contributing_factors JSON NOT NULL DEFAULT '[]', -- [{ factor, weight, source, direction }]
    confidence_interval_lower REAL,                 -- ML model lower bound (e.g., 95% CI)
    confidence_interval_upper REAL,                 -- ML model upper bound (e.g., 95% CI)
    forecast_period_start INTEGER,                  -- Unix timestamp — start of the forecast period
    forecast_period_end   INTEGER,                -- Unix timestamp — end of the forecast period
    model_version       TEXT,                       -- ML model or heuristic identifier + version
    -- Memory metadata
    confidence          REAL NOT NULL DEFAULT 0.5,  -- 0.0–1.0 confidence in this memory record
    generated_by        TEXT NOT NULL,              -- agent name + version (e.g., 'forecast-agent@1.2.0')
    episode_id          TEXT,                       -- link to OODA cycle that produced this memory
    ttl_days            INTEGER NOT NULL DEFAULT 30,  -- Forecast TTL: 30 days per SPINE_DOMAIN.md §4.1
    -- Time bounding
    valid_from          INTEGER,                    -- Unix timestamp — when this memory became valid
    valid_until         INTEGER,                    -- Unix timestamp — NULL = current; set on refresh/replacement
    created_at          INTEGER                     -- Unix timestamp
);

-- Primary lookup: current forecasts for a given Spine entity
CREATE INDEX IF NOT EXISTS idx_memory_forecast_tenant_entity
    ON memory_forecast (tenant_id, entity_type, canonical_id)
    WHERE valid_until IS NULL;

-- Episode traceability: link back to the OODA cycle that generated this memory
CREATE INDEX IF NOT EXISTS idx_memory_forecast_tenant_episode
    ON memory_forecast (tenant_id, episode_id);

-- Query by forecast type (e.g., all churn forecasts for a tenant)
CREATE INDEX IF NOT EXISTS idx_memory_forecast_tenant_type
    ON memory_forecast (tenant_id, forecast_type)
    WHERE valid_until IS NULL;

-- Query by forecast period (e.g., all forecasts covering Q3)
CREATE INDEX IF NOT EXISTS idx_memory_forecast_tenant_period
    ON memory_forecast (tenant_id, forecast_period_start, forecast_period_end)
    WHERE valid_until IS NULL;

-- Score-based filtering (e.g., high-confidence forecasts)
CREATE INDEX IF NOT EXISTS idx_memory_forecast_tenant_confidence
    ON memory_forecast (tenant_id, confidence)
    WHERE valid_until IS NULL;
