-- ============================================================================
-- Memory: Architecture Assessment
-- Layer: Dynamic Memory (AI-Created, Ephemeral, Opinionated)
-- TTL: 90 days
-- Purpose: Evaluated architecture posture derived from API inventory,
--          deployment topology, and integration map. Links to Spine entities
--          (Account, Deployment, Integration, Environment, Product).
-- Source: SPINE_DOMAIN.md §4.1, §4.3 + SPINE_INTELLIGENCE_AGENT.md §7, §10
-- Domain: account_success
-- Generated by: Spine Intelligence Agent — Code Generation Stage (Stage 8)
-- ============================================================================

CREATE TABLE IF NOT EXISTS memory_architecture_assessment (
    id                  TEXT PRIMARY KEY,                         -- UUID as text, assigned by pipeline
    tenant_id           TEXT NOT NULL,                            -- tenant scoping; cross-tenant queries impossible by construction
    -- Link to Canonical Spine (always)
    entity_type         TEXT NOT NULL,                            -- 'account', 'deployment', 'integration', 'environment', 'product'
    canonical_id        TEXT NOT NULL,                            -- stable identity from Spine; survives merges
    -- Memory content (specific to Architecture Assessment)
    score               REAL,                                     -- overall architecture score, 0.0–1.0
    score_label         TEXT,                                     -- 'modern', 'legacy', 'hybrid', 'evolving', 'monolithic', 'distributed'
    reasoning           TEXT,                                     -- LLM-generated or heuristic explanation of assessment
    architecture_pattern TEXT,                                    -- detected pattern: 'microservices', 'monolith', 'serverless', 'event-driven', 'layered', 'modular-monolith'
    integration_complexity TEXT,                                  -- 'low', 'medium', 'high', 'very_high'
    api_maturity_score    REAL,                                   -- API portfolio maturity, 0.0–1.0
    deployment_maturity_score REAL,                             -- deployment topology maturity, 0.0–1.0
    technical_risk_level  TEXT,                                   -- 'low', 'medium', 'high', 'critical'
    contributing_factors  JSON NOT NULL DEFAULT '[]',           -- [{ factor: TEXT, weight: REAL, source: TEXT, evidence: TEXT }]
    recommendations       TEXT,                                   -- suggested architectural improvements
    assessed_at           INTEGER,                              -- Unix timestamp of when source data was assessed
    -- Memory metadata
    confidence          REAL NOT NULL DEFAULT 0.5,              -- 0.0–1.0; this is opinion, not truth
    generated_by        TEXT NOT NULL,                          -- agent name + model version, e.g. 'spine-intelligence-agent@1.0.0/gpt-4o'
    episode_id          TEXT,                                   -- link to OODA cycle that produced this memory
    ttl_days            INTEGER NOT NULL DEFAULT 90,            -- 90 days per SPINE_DOMAIN.md §4.1 Architecture Assessment
    -- Time bounding
    valid_from          INTEGER,                                -- Unix timestamp; when this memory became valid
    valid_until         INTEGER,                                -- NULL = current; set on refresh by Continuity Layer
    created_at          INTEGER                                 -- Unix timestamp; immutable
);

-- Index: active memory lookup by tenant + entity + canonical_id (covers 90% of read queries)
CREATE INDEX IF NOT EXISTS idx_memory_architecture_assessment_tenant_entity
    ON memory_architecture_assessment (tenant_id, entity_type, canonical_id)
    WHERE valid_until IS NULL;

-- Index: episode linkage for OODA cycle tracing and audit
CREATE INDEX IF NOT EXISTS idx_memory_architecture_assessment_episode
    ON memory_architecture_assessment (tenant_id, episode_id);

-- Index: score-based filtering for dashboards and risk prioritization
CREATE INDEX IF NOT EXISTS idx_memory_architecture_assessment_score
    ON memory_architecture_assessment (tenant_id, score)
    WHERE valid_until IS NULL;

-- Index: architecture pattern filtering for cohort analysis and projection slicing
CREATE INDEX IF NOT EXISTS idx_memory_architecture_assessment_pattern
    ON memory_architecture_assessment (tenant_id, architecture_pattern)
    WHERE valid_until IS NULL;
