-- ============================================================================
-- Memory Type: Risk
-- Layer: Dynamic Memory (Layer 2)
-- TTL: 14 days
-- Purpose: Ephemeral, AI-generated risk assessment for a Spine entity.
--          Stores opinionated risk score, reasoning, contributing factors,
--          risk category, indicators, and mitigation suggestions.
--          Refreshed by the Continuity Layer on signal changes.
-- Source: SPINE_DOMAIN.md §4.1, §4.3
--         SPINE_INTELLIGENCE_AGENT.md §7.2, §10.2
-- Domain: account_success
-- ============================================================================

CREATE TABLE IF NOT EXISTS memory_risk (
    -- Identity
    id              TEXT PRIMARY KEY,              -- UUID assigned by the pipeline; not generated by DB
    tenant_id       TEXT NOT NULL,

    -- Spine link (always)
    entity_type     TEXT NOT NULL,                 -- 'account', 'person', 'contract', 'subscription', etc.
    canonical_id    TEXT NOT NULL,                 -- stable Spine identity; survives merges

    -- Memory content (Risk-specific)
    score           REAL,                          -- 0.00–1.00 risk score
    score_label     TEXT,                          -- 'low', 'medium', 'high', 'critical'
    reasoning       TEXT,                          -- LLM-generated or heuristic explanation
    contributing_factors JSON NOT NULL DEFAULT '[]', -- [{ factor, weight, source, confidence }]
    risk_category   TEXT,                          -- 'churn', 'contract', 'technical', 'financial', 'operational', 'expansion'
    risk_indicators JSON NOT NULL DEFAULT '[]',    -- [{ signal, value, threshold, detected_at, source }]
    mitigation_suggestions TEXT,                   -- recommended actions to mitigate risk

    -- Memory metadata
    confidence      REAL NOT NULL DEFAULT 0.5,     -- 0.0–1.0; explicit trust in this memory
    generated_by    TEXT NOT NULL,                 -- agent/model/heuristic name + version
    episode_id      TEXT,                          -- link to OODA cycle that produced this memory

    -- TTL & time bounding
    ttl_days        INTEGER NOT NULL DEFAULT 14,   -- Risk memory TTL: 14 days (SPINE_DOMAIN.md §4.1)
    valid_from      INTEGER,                       -- Unix timestamp; when this memory became valid
    valid_until     INTEGER,                       -- NULL = current; set on refresh or archive
    created_at      INTEGER                        -- Unix timestamp; record creation time
);

-- Core index: look up current risk for a Spine entity (filtered to active memories)
CREATE INDEX IF NOT EXISTS idx_memory_risk_tenant_entity ON memory_risk(tenant_id, entity_type, canonical_id) WHERE valid_until IS NULL;

-- Index: trace risk back to the OODA episode that generated it
CREATE INDEX IF NOT EXISTS idx_memory_risk_episode ON memory_risk(tenant_id, episode_id);

-- Index: filter or sort by risk score for active memories
CREATE INDEX IF NOT EXISTS idx_memory_risk_score ON memory_risk(tenant_id, score) WHERE valid_until IS NULL;
