-- ============================================
-- memory_evidence
-- Layer: Dynamic Memory
-- Purpose: Supporting data for claims — links, metrics, quotes, snapshots.
--   Evidence is persistent (linked to claims) and does not expire by TTL.
--   Generated by the Spine Intelligence Agent during the Signal → Think → Act loop.
--   Links to a Spine entity (via entity_type + canonical_id) and to a specific
--   claim memory (via claim_memory_type + claim_memory_id).
-- TTL: Persistent (linked to claim). ttl_days = 0 means never expires.
-- Source: SPINE_DOMAIN.md §4.1, §4.3 (Dynamic Memory Schema Pattern)
--         SPINE_INTELLIGENCE_AGENT.md §7.2 (Memory Classification)
-- ============================================

CREATE TABLE IF NOT EXISTS memory_evidence (
    id                  TEXT PRIMARY KEY,
    tenant_id           TEXT NOT NULL,
    entity_type         TEXT NOT NULL,              -- links to Spine entity type (e.g., 'account', 'person')
    canonical_id        TEXT NOT NULL,              -- links to Spine canonical_id
    -- Evidence content
    evidence_type       TEXT NOT NULL,              -- 'link', 'metric', 'quote', 'snapshot'
    source              TEXT,                       -- human-readable source name
    source_url          TEXT,                       -- URL if applicable
    content             TEXT,                       -- the actual evidence content (quote, text, etc.)
    metric_value        REAL,                       -- numeric value if evidence_type = 'metric'
    metric_unit         TEXT,                       -- unit of metric if evidence_type = 'metric'
    snapshot_ref        TEXT,                       -- reference to snapshot if evidence_type = 'snapshot'
    claim_memory_type   TEXT,                       -- the memory type this evidence supports (e.g., 'health', 'risk', 'insight')
    claim_memory_id     TEXT,                       -- the id of the specific memory record this supports
    -- Memory metadata
    confidence          REAL NOT NULL DEFAULT 0.5,
    generated_by        TEXT NOT NULL,              -- agent name + version
    episode_id          TEXT,                       -- link to OODA cycle that produced this
    ttl_days            INTEGER NOT NULL DEFAULT 0, -- 0 = persistent (never expires by TTL)
    -- Time bounding
    valid_from          INTEGER,                    -- Unix timestamp
    valid_until         INTEGER,                    -- NULL = current; set on refresh
    created_at          INTEGER                     -- Unix timestamp
);

-- Primary lookup: active evidence for a given Spine entity
CREATE INDEX IF NOT EXISTS idx_memory_evidence_tenant_entity
    ON memory_evidence(tenant_id, entity_type, canonical_id)
    WHERE valid_until IS NULL;

-- Audit: all evidence generated by a given OODA episode
CREATE INDEX IF NOT EXISTS idx_memory_evidence_tenant_episode
    ON memory_evidence(tenant_id, episode_id);

-- Lookup: evidence supporting a specific claim memory
CREATE INDEX IF NOT EXISTS idx_memory_evidence_claim
    ON memory_evidence(tenant_id, claim_memory_type, claim_memory_id);

-- Filter: evidence by type within a tenant
CREATE INDEX IF NOT EXISTS idx_memory_evidence_type
    ON memory_evidence(tenant_id, evidence_type);
