/**
 * MCP Pool - Model Context Protocol Tool Registry
 * All 65+ connectors and integrated tools available to Twin and Workbench
 */

export interface MCPTool {
  id: string;
  name: string;
  category: string;
  provider: string;
  description: string;
  capabilities: string[];
  dataTypes: string[];
  apiType: 'rest' | 'graphql' | 'webhook' | 'sdk';
  requiresAuth: boolean;
  requiredScopes?: string[];
  rateLimit?: { requests: number; window: number };
  webhookSupport: boolean;
  syncModes: ('real-time' | 'polling' | 'webhook')[];
  lifecycleCategories: string[];
}

// CRM & Sales Tools (8 tools)
export const SALES_TOOLS: MCPTool[] = [
  {
    id: 'salesforce',
    name: 'Salesforce',
    category: 'CRM',
    provider: 'Salesforce',
    description: 'Enterprise CRM for sales pipeline, accounts, deals, and forecasting',
    capabilities: ['read_deals', 'create_deals', 'update_deals', 'forecast', 'pipeline_analytics'],
    dataTypes: ['Opportunity', 'Account', 'Contact', 'Lead', 'Forecast'],
    apiType: 'rest',
    requiresAuth: true,
    rateLimit: { requests: 10000, window: 3600 },
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['deal_lifecycle', 'revenue_cycle'],
  },
  {
    id: 'hubspot',
    name: 'HubSpot',
    category: 'CRM',
    provider: 'HubSpot',
    description: 'Marketing, sales, and service CRM with pipeline and contact management',
    capabilities: ['read_deals', 'create_deals', 'update_contacts', 'email_tracking', 'automation'],
    dataTypes: ['Deal', 'Contact', 'Company', 'Ticket', 'Engagement'],
    apiType: 'rest',
    requiresAuth: true,
    rateLimit: { requests: 100, window: 10 },
    webhookSupport: true,
    syncModes: ['webhook'],
    lifecycleCategories: ['sales_cycle', 'customer_lifecycle'],
  },
  {
    id: 'pipedrive',
    name: 'Pipedrive',
    category: 'CRM',
    provider: 'Pipedrive',
    description: 'Visual sales pipeline management and deal tracking',
    capabilities: ['read_deals', 'create_deals', 'update_deals', 'pipeline_views'],
    dataTypes: ['Deal', 'Person', 'Organization', 'Activity'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['deal_lifecycle'],
  },
  {
    id: 'dynamics365',
    name: 'Microsoft Dynamics 365',
    category: 'CRM',
    provider: 'Microsoft',
    description: 'Enterprise CRM with sales, marketing, and customer service',
    capabilities: ['read_opportunities', 'create_opportunities', 'sales_analytics'],
    dataTypes: ['Opportunity', 'Account', 'Contact', 'Case'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['sales_cycle', 'support_cycle'],
  },
  {
    id: 'zoho-crm',
    name: 'Zoho CRM',
    category: 'CRM',
    provider: 'Zoho',
    description: 'Cloud-based CRM for leads, deals, and customer management',
    capabilities: ['read_leads', 'create_deals', 'automation'],
    dataTypes: ['Lead', 'Deal', 'Contact', 'Account'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['webhook'],
    lifecycleCategories: ['lead_lifecycle', 'deal_lifecycle'],
  },
  {
    id: 'freshsales',
    name: 'Freshsales',
    category: 'CRM',
    provider: 'Freshworks',
    description: 'AI-powered sales CRM with built-in call and email',
    capabilities: ['read_deals', 'sales_automation', 'ai_insights'],
    dataTypes: ['Deal', 'Contact', 'Account', 'Activity'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['webhook'],
    lifecycleCategories: ['sales_cycle'],
  },
  {
    id: 'sugarcrm',
    name: 'SugarCRM',
    category: 'CRM',
    provider: 'SugarCRM',
    description: 'Enterprise CRM platform for sales and customer relationships',
    capabilities: ['read_opportunities', 'create_records', 'custom_modules'],
    dataTypes: ['Opportunity', 'Account', 'Contact', 'Custom'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['sales_cycle'],
  },
  {
    id: 'copper',
    name: 'Copper CRM',
    category: 'CRM',
    provider: 'Copper',
    description: 'CRM built for Google Workspace users',
    capabilities: ['read_deals', 'create_opportunities', 'gmail_integration'],
    dataTypes: ['Opportunity', 'Person', 'Company', 'Project'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time'],
    lifecycleCategories: ['deal_lifecycle'],
  },
];

// Customer Success & Support Tools (7 tools)
export const SUPPORT_TOOLS: MCPTool[] = [
  {
    id: 'zendesk',
    name: 'Zendesk',
    category: 'Support',
    provider: 'Zendesk',
    description: 'Customer support and helpdesk platform with ticket management',
    capabilities: ['read_tickets', 'create_tickets', 'close_tickets', 'customer_profiles'],
    dataTypes: ['Ticket', 'User', 'Organization', 'Conversation'],
    apiType: 'rest',
    requiresAuth: true,
    rateLimit: { requests: 300, window: 60 },
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['support_cycle', 'customer_lifecycle'],
  },
  {
    id: 'freshdesk',
    name: 'Freshdesk',
    category: 'Support',
    provider: 'Freshworks',
    description: 'Cloud-based helpdesk software with ticket and knowledge management',
    capabilities: ['read_tickets', 'create_tickets', 'automation'],
    dataTypes: ['Ticket', 'Contact', 'Company', 'Task'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['webhook'],
    lifecycleCategories: ['support_cycle'],
  },
  {
    id: 'intercom',
    name: 'Intercom',
    category: 'Support',
    provider: 'Intercom',
    description: 'Messaging platform for customer communication and support',
    capabilities: ['send_message', 'read_conversations', 'customer_segmentation'],
    dataTypes: ['Conversation', 'Contact', 'Message', 'Company'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['customer_communication'],
  },
  {
    id: 'helpscout',
    name: 'Help Scout',
    category: 'Support',
    provider: 'Help Scout',
    description: 'Help desk software for team collaboration and customer support',
    capabilities: ['read_conversations', 'create_ticket', 'automation'],
    dataTypes: ['Conversation', 'Customer', 'Mailbox'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['webhook'],
    lifecycleCategories: ['support_cycle'],
  },
  {
    id: 'gorgias',
    name: 'Gorgias',
    category: 'Support',
    provider: 'Gorgias',
    description: 'All-in-one customer support platform for ecommerce',
    capabilities: ['read_tickets', 'create_tickets', 'ecommerce_integration'],
    dataTypes: ['Ticket', 'Customer', 'Order', 'Conversation'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['support_cycle', 'sales_cycle'],
  },
  {
    id: 'jira-service-desk',
    name: 'Jira Service Desk',
    category: 'Support',
    provider: 'Atlassian',
    description: 'IT service management and customer support ticketing',
    capabilities: ['read_tickets', 'create_tickets', 'workflow_automation'],
    dataTypes: ['Issue', 'Project', 'Customer', 'Queue'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['support_cycle', 'operations_cycle'],
  },
  {
    id: 'groove',
    name: 'Groove',
    category: 'Support',
    provider: 'Groove',
    description: 'Email-based help desk and customer support platform',
    capabilities: ['read_tickets', 'manage_tickets', 'reporting'],
    dataTypes: ['Ticket', 'Customer', 'Team'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['webhook'],
    lifecycleCategories: ['support_cycle'],
  },
];

// Communication Tools (6 tools)
export const COMMUNICATION_TOOLS: MCPTool[] = [
  {
    id: 'slack',
    name: 'Slack',
    category: 'Communication',
    provider: 'Slack',
    description: 'Team messaging and collaboration platform',
    capabilities: ['send_message', 'read_messages', 'create_channels', 'automation'],
    dataTypes: ['Message', 'Channel', 'User', 'Team'],
    apiType: 'rest',
    requiresAuth: true,
    rateLimit: { requests: 60, window: 60 },
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['team_collaboration', 'notifications'],
  },
  {
    id: 'discord',
    name: 'Discord',
    category: 'Communication',
    provider: 'Discord',
    description: 'Voice, video, and text communication platform',
    capabilities: ['send_message', 'create_channels', 'webhook_notifications'],
    dataTypes: ['Message', 'Channel', 'Guild', 'User'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['webhook'],
    lifecycleCategories: ['team_collaboration'],
  },
  {
    id: 'teams',
    name: 'Microsoft Teams',
    category: 'Communication',
    provider: 'Microsoft',
    description: 'Enterprise messaging and collaboration platform',
    capabilities: ['send_message', 'read_messages', 'automation'],
    dataTypes: ['Message', 'Channel', 'Team', 'User'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['team_collaboration'],
  },
  {
    id: 'email',
    name: 'Email (SMTP/IMAP)',
    category: 'Communication',
    provider: 'Various',
    description: 'Email sending and receipt via SMTP/IMAP protocols',
    capabilities: ['send_email', 'read_emails', 'manage_folders'],
    dataTypes: ['Email', 'Attachment', 'Contact'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['polling'],
    lifecycleCategories: ['customer_communication'],
  },
  {
    id: 'twilio',
    name: 'Twilio',
    category: 'Communication',
    provider: 'Twilio',
    description: 'SMS, voice, and video communication API',
    capabilities: ['send_sms', 'send_call', 'receive_messages', 'transcription'],
    dataTypes: ['Message', 'Call', 'Recording'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['customer_communication'],
  },
  {
    id: 'sendgrid',
    name: 'SendGrid',
    category: 'Communication',
    provider: 'SendGrid',
    description: 'Email delivery and marketing automation platform',
    capabilities: ['send_email', 'manage_lists', 'track_opens'],
    dataTypes: ['Email', 'Contact', 'Campaign'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['webhook'],
    lifecycleCategories: ['marketing_cycle'],
  },
];

// Project & Task Management (6 tools)
export const PROJECT_TOOLS: MCPTool[] = [
  {
    id: 'jira',
    name: 'Jira',
    category: 'Project Management',
    provider: 'Atlassian',
    description: 'Issue and project tracking for software teams',
    capabilities: ['create_issue', 'read_issues', 'update_issue', 'workflow'],
    dataTypes: ['Issue', 'Project', 'Sprint', 'Epic'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['engineering_cycle', 'project_lifecycle'],
  },
  {
    id: 'asana',
    name: 'Asana',
    category: 'Project Management',
    provider: 'Asana',
    description: 'Work management and team collaboration platform',
    capabilities: ['create_task', 'read_tasks', 'update_task', 'project_views'],
    dataTypes: ['Task', 'Project', 'Team', 'Portfolio'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['project_lifecycle'],
  },
  {
    id: 'monday',
    name: 'Monday.com',
    category: 'Project Management',
    provider: 'Monday.com',
    description: 'Work operating system for team collaboration',
    capabilities: ['create_item', 'read_items', 'automation'],
    dataTypes: ['Item', 'Board', 'Group', 'Column'],
    apiType: 'graphql',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['project_lifecycle'],
  },
  {
    id: 'clickup',
    name: 'ClickUp',
    category: 'Project Management',
    provider: 'ClickUp',
    description: 'All-in-one project management and productivity platform',
    capabilities: ['create_task', 'read_tasks', 'manage_spaces'],
    dataTypes: ['Task', 'List', 'Space', 'Team'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['project_lifecycle'],
  },
  {
    id: 'trello',
    name: 'Trello',
    category: 'Project Management',
    provider: 'Trello',
    description: 'Visual project and task management using Kanban boards',
    capabilities: ['create_card', 'read_cards', 'move_card'],
    dataTypes: ['Card', 'Board', 'List', 'Attachment'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['webhook'],
    lifecycleCategories: ['project_lifecycle'],
  },
  {
    id: 'notion',
    name: 'Notion',
    category: 'Project Management',
    provider: 'Notion',
    description: 'All-in-one workspace for notes, databases, and project management',
    capabilities: ['read_pages', 'create_page', 'update_database', 'query'],
    dataTypes: ['Page', 'Database', 'Block', 'Property'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['polling'],
    lifecycleCategories: ['knowledge_management', 'project_lifecycle'],
  },
];

// Code & Development Tools (8 tools)
export const DEVELOPMENT_TOOLS: MCPTool[] = [
  {
    id: 'github',
    name: 'GitHub',
    category: 'Development',
    provider: 'GitHub',
    description: 'Version control and collaboration platform for code',
    capabilities: ['read_repos', 'create_issue', 'manage_pull_requests', 'webhooks'],
    dataTypes: ['Repository', 'Issue', 'Pull Request', 'Commit'],
    apiType: 'rest',
    requiresAuth: true,
    rateLimit: { requests: 5000, window: 3600 },
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['engineering_cycle', 'code_review'],
  },
  {
    id: 'gitlab',
    name: 'GitLab',
    category: 'Development',
    provider: 'GitLab',
    description: 'DevOps platform with version control and CI/CD',
    capabilities: ['read_projects', 'manage_issues', 'merge_requests'],
    dataTypes: ['Project', 'Issue', 'Merge Request', 'Commit'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['engineering_cycle'],
  },
  {
    id: 'bitbucket',
    name: 'Bitbucket',
    category: 'Development',
    provider: 'Atlassian',
    description: 'Git repository management and collaboration',
    capabilities: ['read_repos', 'manage_pull_requests'],
    dataTypes: ['Repository', 'Pull Request', 'Commit', 'Issue'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['engineering_cycle'],
  },
  {
    id: 'linear',
    name: 'Linear',
    category: 'Development',
    provider: 'Linear',
    description: 'Issue tracking and project management for engineers',
    capabilities: ['create_issue', 'read_issues', 'update_status'],
    dataTypes: ['Issue', 'Project', 'Team', 'Cycle'],
    apiType: 'graphql',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['engineering_cycle'],
  },
  {
    id: 'vercel',
    name: 'Vercel',
    category: 'Development',
    provider: 'Vercel',
    description: 'Frontend deployment and infrastructure platform',
    capabilities: ['deploy', 'read_projects', 'manage_deployments'],
    dataTypes: ['Project', 'Deployment', 'Environment'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['engineering_cycle', 'devops_cycle'],
  },
  {
    id: 'heroku',
    name: 'Heroku',
    category: 'Development',
    provider: 'Heroku',
    description: 'Platform as a Service for deploying and managing applications',
    capabilities: ['deploy', 'manage_apps', 'logs'],
    dataTypes: ['App', 'Dyno', 'Release', 'Log'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['engineering_cycle'],
  },
  {
    id: 'datadog',
    name: 'Datadog',
    category: 'Development',
    provider: 'Datadog',
    description: 'Monitoring and observability platform',
    capabilities: ['read_metrics', 'create_alerts', 'dashboards'],
    dataTypes: ['Metric', 'Alert', 'Trace', 'Log'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['operations_cycle', 'monitoring'],
  },
  {
    id: 'sentry',
    name: 'Sentry',
    category: 'Development',
    provider: 'Sentry',
    description: 'Error tracking and performance monitoring',
    capabilities: ['read_events', 'create_issue', 'manage_alerts'],
    dataTypes: ['Event', 'Issue', 'Release', 'Alert'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['monitoring', 'qa_cycle'],
  },
];

// Product & Analytics Tools (6 tools)
export const PRODUCT_TOOLS: MCPTool[] = [
  {
    id: 'amplitude',
    name: 'Amplitude',
    category: 'Analytics',
    provider: 'Amplitude',
    description: 'Product analytics and user behavior tracking',
    capabilities: ['read_events', 'analyze_cohorts', 'dashboards'],
    dataTypes: ['Event', 'User', 'Cohort', 'Funnel'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['product_analytics', 'analytics_cycle'],
  },
  {
    id: 'mixpanel',
    name: 'Mixpanel',
    category: 'Analytics',
    provider: 'Mixpanel',
    description: 'Product analytics with user segmentation and funnels',
    capabilities: ['track_events', 'user_profiles', 'segmentation'],
    dataTypes: ['Event', 'User Profile', 'Cohort'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['product_analytics'],
  },
  {
    id: 'posthog',
    name: 'PostHog',
    category: 'Analytics',
    provider: 'PostHog',
    description: 'Open-source product analytics and feature flags',
    capabilities: ['track_events', 'feature_flags', 'cohorts'],
    dataTypes: ['Event', 'Feature Flag', 'Cohort', 'Person'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['product_analytics'],
  },
  {
    id: 'segment',
    name: 'Segment',
    category: 'Analytics',
    provider: 'Segment',
    description: 'Customer data platform for tracking and unifying data',
    capabilities: ['track_events', 'user_identification', 'destinations'],
    dataTypes: ['Event', 'User', 'Destination', 'Source'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['analytics_cycle', 'data_management'],
  },
  {
    id: 'google-analytics',
    name: 'Google Analytics',
    category: 'Analytics',
    provider: 'Google',
    description: 'Website traffic and user behavior analytics',
    capabilities: ['read_reports', 'events', 'user_reports'],
    dataTypes: ['Event', 'User', 'Session', 'Report'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['polling'],
    lifecycleCategories: ['analytics_cycle', 'marketing_cycle'],
  },
  {
    id: 'heap',
    name: 'Heap',
    category: 'Analytics',
    provider: 'Heap',
    description: 'Automatic event capture and product analytics',
    capabilities: ['read_events', 'user_sessions', 'recordings'],
    dataTypes: ['Event', 'Session', 'Recording', 'User'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['polling'],
    lifecycleCategories: ['product_analytics'],
  },
];

// Finance & Billing Tools (5 tools)
export const FINANCE_TOOLS: MCPTool[] = [
  {
    id: 'stripe',
    name: 'Stripe',
    category: 'Payments',
    provider: 'Stripe',
    description: 'Payment processing and billing platform',
    capabilities: ['create_charge', 'manage_subscriptions', 'invoices'],
    dataTypes: ['Charge', 'Customer', 'Invoice', 'Subscription'],
    apiType: 'rest',
    requiresAuth: true,
    rateLimit: { requests: 100, window: 1 },
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['payment_cycle', 'revenue_cycle'],
  },
  {
    id: 'quickbooks',
    name: 'QuickBooks',
    category: 'Accounting',
    provider: 'Intuit',
    description: 'Accounting software for invoicing and financial management',
    capabilities: ['read_invoices', 'create_invoice', 'manage_accounts'],
    dataTypes: ['Invoice', 'Payment', 'Account', 'Transaction'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['accounting_cycle', 'revenue_cycle'],
  },
  {
    id: 'xero',
    name: 'Xero',
    category: 'Accounting',
    provider: 'Xero',
    description: 'Cloud accounting software for small businesses',
    capabilities: ['read_invoices', 'create_invoice', 'reporting'],
    dataTypes: ['Invoice', 'Contact', 'Account', 'Transaction'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['accounting_cycle'],
  },
  {
    id: 'chargebee',
    name: 'Chargebee',
    category: 'Billing',
    provider: 'Chargebee',
    description: 'Subscription and recurring billing management',
    capabilities: ['manage_subscriptions', 'invoicing', 'analytics'],
    dataTypes: ['Subscription', 'Invoice', 'Customer', 'Plan'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['billing_cycle', 'revenue_cycle'],
  },
  {
    id: 'plaid',
    name: 'Plaid',
    category: 'Finance',
    provider: 'Plaid',
    description: 'Financial data connectivity and account linking',
    capabilities: ['link_accounts', 'read_transactions', 'account_details'],
    dataTypes: ['Account', 'Transaction', 'Balance', 'Institution'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['finance_cycle'],
  },
];

// Marketing & Content Tools (6 tools)
export const MARKETING_TOOLS: MCPTool[] = [
  {
    id: 'mailchimp',
    name: 'Mailchimp',
    category: 'Email Marketing',
    provider: 'Mailchimp',
    description: 'Email marketing and automation platform',
    capabilities: ['send_campaign', 'manage_lists', 'automation'],
    dataTypes: ['Campaign', 'List', 'Contact', 'Automation'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['marketing_cycle'],
  },
  {
    id: 'klaviyo',
    name: 'Klaviyo',
    category: 'Email Marketing',
    provider: 'Klaviyo',
    description: 'Email marketing and SMS platform for ecommerce',
    capabilities: ['send_email', 'send_sms', 'segmentation'],
    dataTypes: ['Campaign', 'List', 'Profile', 'Event'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['marketing_cycle'],
  },
  {
    id: 'facebook-ads',
    name: 'Facebook Ads Manager',
    category: 'Advertising',
    provider: 'Meta',
    description: 'Social media advertising and campaign management',
    capabilities: ['create_campaign', 'manage_ads', 'analytics'],
    dataTypes: ['Campaign', 'Ad', 'Insight', 'Audience'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['marketing_cycle'],
  },
  {
    id: 'google-ads',
    name: 'Google Ads',
    category: 'Advertising',
    provider: 'Google',
    description: 'Search and display advertising platform',
    capabilities: ['manage_campaigns', 'manage_ads', 'reporting'],
    dataTypes: ['Campaign', 'Ad Group', 'Ad', 'Keyword'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['polling'],
    lifecycleCategories: ['marketing_cycle'],
  },
  {
    id: 'hubspot-marketing',
    name: 'HubSpot Marketing',
    category: 'Email Marketing',
    provider: 'HubSpot',
    description: 'Email marketing, landing pages, and forms',
    capabilities: ['send_email', 'create_forms', 'automation'],
    dataTypes: ['Email', 'Form', 'Landing Page', 'Contact'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['marketing_cycle'],
  },
  {
    id: 'content-calendar',
    name: 'Content Calendar',
    category: 'Content Management',
    provider: 'Various',
    description: 'Content planning and scheduling',
    capabilities: ['plan_content', 'schedule_posts', 'collaboration'],
    dataTypes: ['Content', 'Schedule', 'Team', 'Calendar'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['polling'],
    lifecycleCategories: ['content_cycle'],
  },
];

// Design & Collaboration Tools (5 tools)
export const DESIGN_TOOLS: MCPTool[] = [
  {
    id: 'figma',
    name: 'Figma',
    category: 'Design',
    provider: 'Figma',
    description: 'Collaborative design and prototyping platform',
    capabilities: ['read_files', 'read_components', 'collaborate'],
    dataTypes: ['File', 'Frame', 'Component', 'Comment'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['design_cycle', 'collaboration'],
  },
  {
    id: 'adobe-xd',
    name: 'Adobe XD',
    category: 'Design',
    provider: 'Adobe',
    description: 'User experience design and collaboration tool',
    capabilities: ['read_files', 'share_prototypes', 'collaborate'],
    dataTypes: ['Document', 'Artboard', 'Component', 'Prototype'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['polling'],
    lifecycleCategories: ['design_cycle'],
  },
  {
    id: 'miro',
    name: 'Miro',
    category: 'Collaboration',
    provider: 'Miro',
    description: 'Visual collaboration whiteboard platform',
    capabilities: ['create_board', 'add_objects', 'collaborate'],
    dataTypes: ['Board', 'Object', 'Frame', 'Comment'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['collaboration', 'brainstorming'],
  },
  {
    id: 'confluence',
    name: 'Confluence',
    category: 'Documentation',
    provider: 'Atlassian',
    description: 'Team collaboration and documentation platform',
    capabilities: ['read_pages', 'create_page', 'manage_spaces'],
    dataTypes: ['Page', 'Space', 'Comment', 'Attachment'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['knowledge_management'],
  },
  {
    id: 'coda',
    name: 'Coda',
    category: 'Collaboration',
    provider: 'Coda',
    description: 'All-in-one collaborative workspace',
    capabilities: ['read_docs', 'create_doc', 'tables', 'automation'],
    dataTypes: ['Doc', 'Table', 'View', 'Formula'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['knowledge_management', 'collaboration'],
  },
];

// AI & ML Tools (7 tools)
export const AI_TOOLS: MCPTool[] = [
  {
    id: 'openai',
    name: 'OpenAI',
    category: 'AI',
    provider: 'OpenAI',
    description: 'GPT models for text generation and intelligence',
    capabilities: ['completions', 'embeddings', 'fine_tuning'],
    dataTypes: ['Completion', 'Embedding', 'Model'],
    apiType: 'rest',
    requiresAuth: true,
    rateLimit: { requests: 90000, window: 60 },
    webhookSupport: false,
    syncModes: ['real-time'],
    lifecycleCategories: ['ai_cycle', 'nlp'],
  },
  {
    id: 'anthropic',
    name: 'Anthropic Claude',
    category: 'AI',
    provider: 'Anthropic',
    description: 'Claude language model for text generation',
    capabilities: ['completions', 'vision', 'tool_use'],
    dataTypes: ['Completion', 'Message'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['real-time'],
    lifecycleCategories: ['ai_cycle'],
  },
  {
    id: 'cohere',
    name: 'Cohere',
    category: 'AI',
    provider: 'Cohere',
    description: 'NLP models for text generation and embeddings',
    capabilities: ['generate_text', 'embeddings', 'classify'],
    dataTypes: ['Generation', 'Embedding', 'Classification'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['real-time'],
    lifecycleCategories: ['ai_cycle', 'nlp'],
  },
  {
    id: 'huggingface',
    name: 'Hugging Face',
    category: 'AI',
    provider: 'Hugging Face',
    description: 'Open-source ML models and hub',
    capabilities: ['inference', 'model_access', 'datasets'],
    dataTypes: ['Model', 'Dataset', 'Inference Result'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['real-time'],
    lifecycleCategories: ['ai_cycle'],
  },
  {
    id: 'fal-ai',
    name: 'fal.ai',
    category: 'AI',
    provider: 'fal.ai',
    description: 'Image generation and computer vision models',
    capabilities: ['generate_image', 'process_image', 'vision'],
    dataTypes: ['Image', 'Generation Result', 'Analysis'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['real-time'],
    lifecycleCategories: ['ai_cycle', 'media_generation'],
  },
  {
    id: 'deepinfra',
    name: 'Deep Infra',
    category: 'AI',
    provider: 'Deep Infra',
    description: 'Serverless inference for open-source models',
    capabilities: ['inference', 'text_generation', 'embeddings'],
    dataTypes: ['Inference Result', 'Generation', 'Embedding'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['real-time'],
    lifecycleCategories: ['ai_cycle'],
  },
  {
    id: 'llama-index',
    name: 'LlamaIndex',
    category: 'AI',
    provider: 'LlamaIndex',
    description: 'Data framework for LLM applications',
    capabilities: ['indexing', 'querying', 'rag'],
    dataTypes: ['Index', 'Query Result', 'Document'],
    apiType: 'sdk',
    requiresAuth: false,
    webhookSupport: false,
    syncModes: ['real-time'],
    lifecycleCategories: ['knowledge_management', 'ai_cycle'],
  },
];

// Storage & Data Tools (5 tools)
export const DATA_TOOLS: MCPTool[] = [
  {
    id: 'supabase',
    name: 'Supabase',
    category: 'Database',
    provider: 'Supabase',
    description: 'Open-source Firebase alternative with Postgres',
    capabilities: ['read_data', 'write_data', 'real_time'],
    dataTypes: ['Table', 'Row', 'Function', 'Storage'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['data_management'],
  },
  {
    id: 'firebase',
    name: 'Firebase',
    category: 'Backend',
    provider: 'Google',
    description: 'Backend-as-a-service platform',
    capabilities: ['read_data', 'write_data', 'auth', 'functions'],
    dataTypes: ['Document', 'Collection', 'File', 'Event'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['data_management'],
  },
  {
    id: 'mongodb',
    name: 'MongoDB',
    category: 'Database',
    provider: 'MongoDB',
    description: 'NoSQL document database',
    capabilities: ['read_documents', 'write_documents', 'aggregation'],
    dataTypes: ['Document', 'Collection', 'Database'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['data_management'],
  },
  {
    id: 'airtable',
    name: 'Airtable',
    category: 'Data',
    provider: 'Airtable',
    description: 'Flexible database and spreadsheet hybrid',
    capabilities: ['read_records', 'create_record', 'update_record'],
    dataTypes: ['Base', 'Table', 'Record', 'Field'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['data_management'],
  },
  {
    id: 'snowflake',
    name: 'Snowflake',
    category: 'Data Warehouse',
    provider: 'Snowflake',
    description: 'Cloud data warehouse for analytics',
    capabilities: ['query_data', 'load_data', 'analytics'],
    dataTypes: ['Table', 'Schema', 'View', 'Query Result'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['polling'],
    lifecycleCategories: ['analytics_cycle', 'data_warehouse'],
  },
];

// Media & Hosting Tools (5 tools)
export const MEDIA_TOOLS: MCPTool[] = [
  {
    id: 'cloudinary',
    name: 'Cloudinary',
    category: 'Media',
    provider: 'Cloudinary',
    description: 'Image and video management and optimization',
    capabilities: ['upload_image', 'transform', 'analytics'],
    dataTypes: ['Image', 'Video', 'Asset', 'Transformation'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['media_management'],
  },
  {
    id: 's3',
    name: 'AWS S3',
    category: 'Storage',
    provider: 'AWS',
    description: 'Object storage service',
    capabilities: ['upload_object', 'download_object', 'list_objects'],
    dataTypes: ['Object', 'Bucket', 'Version'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['media_management', 'data_storage'],
  },
  {
    id: 'cloudflare-r2',
    name: 'Cloudflare R2',
    category: 'Storage',
    provider: 'Cloudflare',
    description: 'S3-compatible object storage',
    capabilities: ['upload_object', 'download_object'],
    dataTypes: ['Object', 'Bucket'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['real-time'],
    lifecycleCategories: ['media_management'],
  },
  {
    id: 'youtube',
    name: 'YouTube',
    category: 'Media',
    provider: 'Google',
    description: 'Video hosting and streaming',
    capabilities: ['upload_video', 'manage_playlist', 'analytics'],
    dataTypes: ['Video', 'Playlist', 'Channel', 'Engagement'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['polling'],
    lifecycleCategories: ['media_management', 'content_cycle'],
  },
  {
    id: 'vimeo',
    name: 'Vimeo',
    category: 'Media',
    provider: 'Vimeo',
    description: 'Professional video hosting',
    capabilities: ['upload_video', 'manage_folder', 'analytics'],
    dataTypes: ['Video', 'Folder', 'Viewer', 'Interaction'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['media_management'],
  },
];

// Compliance & Monitoring Tools (4 tools)
export const COMPLIANCE_TOOLS: MCPTool[] = [
  {
    id: 'okta',
    name: 'Okta',
    category: 'Identity',
    provider: 'Okta',
    description: 'Identity and access management',
    capabilities: ['manage_users', 'manage_groups', 'audit_logs'],
    dataTypes: ['User', 'Group', 'Policy', 'Log'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['security_cycle', 'governance'],
  },
  {
    id: 'jump-cloud',
    name: 'JumpCloud',
    category: 'Identity',
    provider: 'JumpCloud',
    description: 'Directory and access management',
    capabilities: ['manage_users', 'device_management', 'mfa'],
    dataTypes: ['User', 'Device', 'System'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['security_cycle'],
  },
  {
    id: 'vault',
    name: 'HashiCorp Vault',
    category: 'Security',
    provider: 'HashiCorp',
    description: 'Secrets and encryption management',
    capabilities: ['store_secret', 'retrieve_secret', 'rotate_credentials'],
    dataTypes: ['Secret', 'Key', 'Token'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: false,
    syncModes: ['real-time'],
    lifecycleCategories: ['security_cycle'],
  },
  {
    id: 'wiz',
    name: 'Wiz',
    category: 'Security',
    provider: 'Wiz',
    description: 'Cloud security posture management',
    capabilities: ['scan_infrastructure', 'vulnerabilities', 'compliance'],
    dataTypes: ['Issue', 'Resource', 'Vulnerability'],
    apiType: 'rest',
    requiresAuth: true,
    webhookSupport: true,
    syncModes: ['real-time', 'webhook'],
    lifecycleCategories: ['security_cycle', 'compliance_cycle'],
  },
];

// All tools registry
export const ALL_MCP_TOOLS = [
  ...SALES_TOOLS,
  ...SUPPORT_TOOLS,
  ...COMMUNICATION_TOOLS,
  ...PROJECT_TOOLS,
  ...DEVELOPMENT_TOOLS,
  ...PRODUCT_TOOLS,
  ...FINANCE_TOOLS,
  ...MARKETING_TOOLS,
  ...DESIGN_TOOLS,
  ...AI_TOOLS,
  ...DATA_TOOLS,
  ...MEDIA_TOOLS,
  ...COMPLIANCE_TOOLS,
];

// MCP Pool categories
export const MCP_CATEGORIES = {
  sales: SALES_TOOLS,
  support: SUPPORT_TOOLS,
  communication: COMMUNICATION_TOOLS,
  projects: PROJECT_TOOLS,
  development: DEVELOPMENT_TOOLS,
  product: PRODUCT_TOOLS,
  finance: FINANCE_TOOLS,
  marketing: MARKETING_TOOLS,
  design: DESIGN_TOOLS,
  ai: AI_TOOLS,
  data: DATA_TOOLS,
  media: MEDIA_TOOLS,
  compliance: COMPLIANCE_TOOLS,
};

export function getTotalToolCount(): number {
  return ALL_MCP_TOOLS.length;
}

export function getToolsByCategory(category: keyof typeof MCP_CATEGORIES): MCPTool[] {
  return MCP_CATEGORIES[category] || [];
}

export function getToolById(id: string): MCPTool | undefined {
  return ALL_MCP_TOOLS.find(t => t.id === id);
}

export function getToolsByLifecycle(lifecycle: string): MCPTool[] {
  return ALL_MCP_TOOLS.filter(t => t.lifecycleCategories.includes(lifecycle));
}
